name: Build and Push Docker Image to Artifact Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: medical-image-annotator
  SERVICE_NAME: auth-service 
  REGION: europe-west3
  REPO_NAME: docker-repo

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Authenticate to GCP
      id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Configure Docker to use Artifact Registry as credential helper
      run: |
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

    - name: Build and push Docker image to Artifact Registry
      run: |
        IMAGE_URI="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA"
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI
