- name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${REPO_NAME} \
            --image ${REGION}-docker.pkg.dev/${PROJECT_ID}/histopath-docker-repo/${REPO_NAME}:latest \
            --region ${REGION} \
            --platform managed \
            --allow-unauthenticated \
            --timeout=300s \
            --set-env-vars=PROJECT_ID=${PROJECT_ID},REGION=${REGION},ENV=prod,GIN_MODE=release,READ_TIMEOUT=15,WRITE_TIMEOUT=15,IDLE_TIMEOUT=60,PROJECT_NUMBER=${PROJECT_NUMBER},IMAGE_CATALOG_SERVICE_NAME=${IMAGE_CATALOG_SERVICE_NAME},PORT=8080